# Generated by Django 4.0.2 on 2023-05-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SubjectList', '0005_alter_course_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='KCSEExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('unit', models.CharField(max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.course')),
            ],
        ),
        migrations.CreateModel(
            name='KCSEQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('quiz', models.TextField(max_length=500)),
                ('number', models.CharField(max_length=10)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.kcseexam')),
            ],
        ),
        migrations.CreateModel(
            name='KCSEAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=500)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.kcsequiz')),
            ],
        ),
    ]
