# Generated by Django 4.0.2 on 2023-06-15 18:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SubjectList', '0009_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicalQuizes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quiz', models.TextField(max_length=500)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.topic')),
            ],
        ),
    ]
