# Generated by Django 4.0.2 on 2023-06-15 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TABLE exams_temp (id INT);"
        ),
    ]
