# Generated by Django 4.0.2 on 2023-05-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcseanswers',
            name='answer',
            field=models.TextField(max_length=1500),
        ),
    ]
