# Generated by Django 4.0.2 on 2023-06-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0002_alter_kcseanswers_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcsequiz',
            name='number',
            field=models.IntegerField(),
        ),
    ]
