# Generated by Django 4.0.2 on 2023-06-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0003_studenttest_studentsanswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttest',
            name='quiz',
        ),
    ]
