# Generated by Django 4.0.2 on 2023-06-13 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0008_topic_order'),
        ('Exams', '0003_alter_kcsequiz_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicalQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.TextField(max_length=500)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicalQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=500)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.topicalquiz')),
            ],
        ),
    ]
