# Generated by Django 4.0.2 on 2023-06-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0004_topicalquiz_topicalquizanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicalquizanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='topicalquizanswer',
            name='a',
            field=models.CharField(default='nul', max_length=500),
        ),
        migrations.AddField(
            model_name='topicalquizanswer',
            name='b',
            field=models.CharField(default='nul', max_length=500),
        ),
        migrations.AddField(
            model_name='topicalquizanswer',
            name='c',
            field=models.CharField(default='nul', max_length=500),
        ),
        migrations.AddField(
            model_name='topicalquizanswer',
            name='correct',
            field=models.CharField(default='nul', max_length=500),
        ),
    ]
