# Generated by Django 4.0.2 on 2023-06-18 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0024_alter_progress_subject_alter_topic_subject'),
        ('Exams', '0005_remove_studentsanswers_id_alter_studentsanswers_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='subject',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject'),
        ),
    ]
