# Generated by Django 4.0.2 on 2023-06-19 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0024_alter_progress_subject_alter_topic_subject'),
        ('Exams', '0006_studenttest_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='marks',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsanswers',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.studenttest', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject'),
        ),
    ]
