# Generated by Django 4.0.2 on 2023-06-19 12:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0008_alter_studentsanswers_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsanswers',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.studenttest', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
