# Generated by Django 4.0.2 on 2023-06-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0009_alter_studentsanswers_test_alter_studenttest_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsanswers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
