# Generated by Django 4.2.3 on 2023-07-13 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0062_accountinquiries_academicinquiries'),
        ('Exams', '0010_studentsanswers_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicalquizes',
            name='subject',
            field=models.ForeignKey(default='9', on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject'),
        ),
        migrations.AddField(
            model_name='topicalquizes',
            name='subtopic',
            field=models.ForeignKey(default='c3d84221-3f51-4116-a81a-7e1c5bf71360', on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subtopic'),
        ),
    ]
