# Generated by Django 4.2.3 on 2023-07-13 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0062_accountinquiries_academicinquiries'),
        ('Exams', '0011_topicalquizes_subject_topicalquizes_subtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicalquizes',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject'),
        ),
        migrations.AlterField(
            model_name='topicalquizes',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subtopic'),
        ),
    ]
