# Generated by Django 4.2.3 on 2023-08-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0013_studenttest_duration_studenttest_test_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='quiz',
            field=models.ManyToManyField(to='Exams.topicalquizes'),
        ),
    ]
