# Generated by Django 4.2.3 on 2023-08-11 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0066_alter_classbookingnotifications_date_and_more'),
        ('Exams', '0014_studenttest_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsanswers',
            name='test',
        ),
        migrations.RemoveField(
            model_name='studentsanswers',
            name='uuid',
        ),
        migrations.AddField(
            model_name='studentsanswers',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SubjectList.topic'),
        ),
    ]
