# Generated by Django 4.2.3 on 2023-08-11 04:30

import Exams.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Exams', '0015_remove_studentsanswers_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsanswers',
            name='test_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='studentsanswers',
            name='test_object_id',
            field=models.UUIDField(default=Exams.models.generate_uuid, editable=False),
        ),
    ]
