# Generated by Django 4.2.3 on 2023-08-11 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0066_alter_classbookingnotifications_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Exams', '0017_classtest_alter_studentsanswers_test_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('marks', models.CharField(default='0', max_length=100)),
                ('test_size', models.PositiveIntegerField(default=15)),
                ('duration', models.PositiveIntegerField(default=15)),
                ('exam_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SubjectList.topic')),
                ('quiz', models.ManyToManyField(to='Exams.topicalquizes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
