# Generated by Django 4.2.3 on 2023-08-12 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SubjectList', '0066_alter_classbookingnotifications_date_and_more'),
        ('Exams', '0018_generaltest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaltest',
            name='exam_type',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.CreateModel(
            name='StudentKNECExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('marks', models.CharField(default='0', max_length=100)),
                ('test_size', models.PositiveIntegerField(default=15)),
                ('duration', models.PositiveIntegerField(default=15)),
                ('exam_type', models.CharField(default='general', max_length=100)),
                ('expiry', models.DateField()),
                ('quiz', models.ManyToManyField(to='Exams.topicalquizes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KNECGradeExams',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('test_size', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(default='15')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.DateField()),
                ('grade', models.CharField(max_length=2)),
                ('quiz', models.ManyToManyField(to='Exams.topicalquizes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
