# Generated by Django 4.2.3 on 2023-08-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0022_studentknecexams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentknecexams',
            name='expiry',
        ),
    ]
