# Generated by Django 4.2.3 on 2023-08-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0023_remove_studentknecexams_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentknecexams',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
