# Generated by Django 4.2.3 on 2023-08-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0024_alter_studentknecexams_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='knecgradeexams',
            name='term',
            field=models.CharField(default='2', max_length=100),
        ),
        migrations.AddField(
            model_name='knecgradeexams',
            name='year',
            field=models.CharField(default='2023', max_length=6),
        ),
    ]
