# Generated by Django 4.2.3 on 2023-08-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0025_knecgradeexams_term_knecgradeexams_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtest',
            name='expiry',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='knecgradeexams',
            name='expiry',
            field=models.DateField(null=True),
        ),
    ]
