# Generated by Django 4.2.3 on 2023-08-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0001_initial'),
        ('Exams', '0026_alter_classtest_expiry_alter_knecgradeexams_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knecgradeexams',
            name='quiz',
            field=models.ManyToManyField(to='Supervisor.knecquizzes'),
        ),
    ]
