# Generated by Django 4.2.3 on 2023-08-16 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supervisor', '0002_schools'),
        ('Exams', '0027_alter_knecgradeexams_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsKnecAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('is_correct', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supervisor.knecquizzes')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supervisor.knecquizanswers')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.studentknecexams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
