# Generated by Django 4.2.3 on 2023-09-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='caller',
            new_name='user',
        ),
        migrations.AddField(
            model_name='logentry',
            name='error_type',
            field=models.CharField(default=KeyError, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='school',
            field=models.UUIDField(),
        ),
    ]
