# Generated by Django 4.2.3 on 2023-09-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0002_rename_caller_logentry_user_logentry_error_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='app_name',
            field=models.CharField(default='Users.views', max_length=100),
            preserve_default=False,
        ),
    ]
