# Generated by Django 4.2.3 on 2023-09-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0003_logentry_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='object_id',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
