# Generated by Django 4.0.2 on 2023-05-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0002_course_topic_subtopic_mysubjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
    ]
