# Generated by Django 4.0.2 on 2023-05-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0003_remove_course_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.CharField(default='science', max_length=2),
        ),
    ]
