# Generated by Django 4.0.2 on 2023-05-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0004_course_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discipline',
            field=models.CharField(default='science', max_length=20),
        ),
    ]
