# Generated by Django 4.0.2 on 2023-06-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0005_alter_course_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='file',
            field=models.FileField(default='file.pdf', upload_to='studyFiles'),
        ),
    ]
