# Generated by Django 4.0.2 on 2023-06-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0007_alter_subtopic_topic_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
