# Generated by Django 4.0.2 on 2023-06-16 13:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0009_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
