# Generated by Django 4.0.2 on 2023-06-16 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0010_notifications_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='SubjectList.topic'),
        ),
    ]
