# Generated by Django 4.0.2 on 2023-06-16 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SubjectList', '0013_alter_progress_topic_alter_progress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='subtopic',
        ),
        migrations.AlterField(
            model_name='progress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='SubjectList.subject'),
        ),
    ]
