# Generated by Django 4.0.2 on 2023-06-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0014_remove_progress_subject_remove_progress_subtopic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='topic',
        ),
        migrations.AddField(
            model_name='progress',
            name='topic',
            field=models.ManyToManyField(related_name='progress', to='SubjectList.Topic'),
        ),
    ]
