# Generated by Django 4.0.2 on 2023-06-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0015_remove_progress_topic_progress_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysubjects',
            name='name',
            field=models.ManyToManyField(blank=True, related_name='ui', to='SubjectList.Course'),
        ),
    ]
