# Generated by Django 4.0.2 on 2023-06-17 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0017_alter_progress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='topic',
            field=models.ManyToManyField(to='SubjectList.Topic'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='SubjectList.mysubjects'),
        ),
    ]
