# Generated by Django 4.0.2 on 2023-06-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0018_alter_progress_topic_alter_progress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysubjects',
            name='name',
            field=models.ManyToManyField(blank=True, related_name='my_subjects', to='SubjectList.Course'),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
