# Generated by Django 4.0.2 on 2023-06-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0020_alter_topic_subject_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='subject',
        ),
        migrations.AddField(
            model_name='progress',
            name='subject',
            field=models.ManyToManyField(to='SubjectList.Subject'),
        ),
    ]
