# Generated by Django 4.0.2 on 2023-06-18 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0023_remove_progress_subject_progress_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_id', to='SubjectList.subject'),
        ),
    ]
