# Generated by Django 4.0.2 on 2023-06-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0025_alter_notifications_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='topics',
            field=models.PositiveIntegerField(default='6'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='uuid',
            field=models.CharField(default='<function uuid4 at 0x000001C9D173EE50>', max_length=100, unique=True),
        ),
    ]
