# Generated by Django 4.0.2 on 2023-06-23 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0038_alter_notifications_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='uuid',
            field=models.CharField(default='<function uuid4 at 0x000001D5B8BAEE50>', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject'),
        ),
    ]
