# Generated by Django 4.0.2 on 2023-06-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0042_alter_notifications_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='order',
            field=models.CharField(default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='uuid',
            field=models.CharField(default='<function uuid4 at 0x000001A4D036FE50>', max_length=100, unique=True),
        ),
    ]
