# Generated by Django 4.0.2 on 2023-06-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0043_subtopic_order_alter_notifications_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topics_count',
            field=models.CharField(default='4', max_length=5),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='uuid',
            field=models.CharField(default='<function uuid4 at 0x0000018F9972FE50>', max_length=100, unique=True),
        ),
    ]
