# Generated by Django 4.0.2 on 2023-06-25 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0044_topic_topics_count_alter_notifications_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='subject',
            field=models.ForeignKey(default='9', on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='uuid',
            field=models.CharField(default='<function uuid4 at 0x000001A3FC97FE50>', max_length=100, unique=True),
        ),
    ]
