# Generated by Django 4.0.2 on 2023-06-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0046_alter_notifications_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
