# Generated by Django 4.0.2 on 2023-06-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0047_subject_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='uuid',
            field=models.CharField(default='<function uuid4 at 0x000001C6BAE9FE50>', editable=False, max_length=100, unique=True),
        ),
    ]
