# Generated by Django 4.0.2 on 2023-06-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0048_alter_notifications_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
