# Generated by Django 4.0.2 on 2023-06-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0051_alter_notifications_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
