# Generated by Django 4.0.2 on 2023-06-29 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0054_videochannel_onlineclass_classbooking_agoralearners'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochannel',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SubjectList.onlineclass'),
            preserve_default=False,
        ),
    ]
