# Generated by Django 4.0.2 on 2023-06-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0055_videochannel_class_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicExamNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('about', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.topic')),
            ],
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
