# Generated by Django 4.2.3 on 2023-07-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0058_paymentnotifications_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='classbookingnotifications',
            name='notification_type',
            field=models.CharField(default='payment', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentnotifications',
            name='notification_type',
            field=models.CharField(default='payment', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionnotifications',
            name='notification_type',
            field=models.CharField(default='payment', max_length=100),
        ),
        migrations.AddField(
            model_name='topicalexamresults',
            name='notification_type',
            field=models.CharField(default='payment', max_length=100),
        ),
        migrations.AddField(
            model_name='topicexamnotifications',
            name='notification_type',
            field=models.CharField(default='payment', max_length=100),
        ),
    ]
