# Generated by Django 4.2.3 on 2023-07-07 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0059_classbookingnotifications_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicalexamresults',
            name='test',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
