# Generated by Django 4.2.3 on 2023-07-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0060_topicalexamresults_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicalexamresults',
            name='test',
            field=models.UUIDField(),
        ),
    ]
