# Generated by Django 4.2.3 on 2023-08-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0062_accountinquiries_academicinquiries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicalexamresults',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SubjectList.topic'),
        ),
    ]
