# Generated by Django 4.2.3 on 2023-08-05 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0063_alter_topicalexamresults_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicexamnotifications',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SubjectList.topic'),
        ),
    ]
