# Generated by Django 4.2.3 on 2023-08-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0065_classbookingnotifications_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classbookingnotifications',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='paymentnotifications',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='subscriptionnotifications',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='topicalexamresults',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='topicexamnotifications',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
