# Generated by Django 4.0.2 on 2023-06-23 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0003_stripecardpayments_student_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysubscription',
            name='expiry',
            field=models.DateField(auto_created=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='mysubscription',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
