# Generated by Django 4.0.2 on 2023-06-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0004_mysubscription_expiry_mysubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecardpayments',
            name='type',
            field=models.CharField(default='Platinum', max_length=100),
        ),
    ]
