# Generated by Django 4.2.3 on 2023-07-14 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SubjectList', '0062_accountinquiries_academicinquiries'),
        ('Teacher', '0002_alter_studentlist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.onlineclass')),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_class', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
