# Generated by Django 4.2.3 on 2023-07-17 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Exams', '0012_alter_topicalquizes_subject_and_more'),
        ('SubjectList', '0062_accountinquiries_academicinquiries'),
        ('Teacher', '0003_myclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='subject',
            field=models.OneToOneField(default='9', on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject'),
        ),
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('date', models.DateTimeField(auto_created=True)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('test_size', models.PositiveIntegerField()),
                ('expiry', models.DateField()),
                ('quiz', models.ManyToManyField(to='Exams.topicalquizes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
