# Generated by Django 4.2.3 on 2023-07-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_studentlist_subject_classtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
