# Generated by Django 4.2.3 on 2023-07-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0006_schoolclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
