# Generated by Django 4.2.3 on 2023-07-18 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0062_accountinquiries_academicinquiries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0012_academicprofile_current_class'),
        ('Teacher', '0007_delete_schoolclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlist',
            name='students',
        ),
        migrations.AddField(
            model_name='classtest',
            name='class_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Users.schoolclass'),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='class_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Users.schoolclass'),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='subject',
            field=models.ForeignKey(default='9', on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject'),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
