# Generated by Django 4.2.3 on 2023-07-18 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0012_alter_topicalquizes_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teacher', '0008_remove_studentlist_students_classtest_class_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtest',
            name='duration',
            field=models.PositiveIntegerField(default='15'),
        ),
        migrations.CreateModel(
            name='ClassTestStudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('marks', models.CharField(default='0', max_length=100)),
                ('finished', models.BooleanField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.classtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='classTestStudentAnswers',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.topicalquizes')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.topicalquizanswers')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.classtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
