# Generated by Django 4.2.3 on 2023-07-20 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectList', '0062_accountinquiries_academicinquiries'),
        ('Users', '0012_academicprofile_current_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teacher', '0009_classtest_duration_classteststudenttest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTestNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('notification_type', models.CharField(default='payment', max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('about', models.CharField(max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.classtest')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SubjectList.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
