# Generated by Django 4.2.3 on 2023-08-10 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0011_alter_classtestnotifications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtestnotifications',
            name='date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 8, 10, 15, 56, 59, 202124)),
        ),
    ]
