# Generated by Django 4.2.3 on 2023-08-11 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0017_classtest_alter_studentsanswers_test_object_id_and_more'),
        ('Teacher', '0014_delete_classteststudentanswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classteststudenttest',
            name='test',
        ),
        migrations.RemoveField(
            model_name='classteststudenttest',
            name='user',
        ),
        migrations.AlterField(
            model_name='classtestnotifications',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.classtest'),
        ),
        migrations.DeleteModel(
            name='ClassTest',
        ),
        migrations.DeleteModel(
            name='ClassTestStudentTest',
        ),
    ]
