# Generated by Django 4.2.3 on 2023-08-15 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SubjectList', '0066_alter_classbookingnotifications_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnecQuizzes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quiz', models.TextField(max_length=500)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subject')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectList.topic')),
            ],
        ),
        migrations.CreateModel(
            name='KnecQuizAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('choice', models.CharField(max_length=600)),
                ('is_correct', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supervisor.knecquizzes')),
            ],
        ),
    ]
