# Generated by Django 4.2.3 on 2023-08-16 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('school_type', models.CharField(default='Primary', max_length=100)),
            ],
        ),
    ]
