# Generated by Django 4.0.2 on 2023-05-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='area',
            field=models.CharField(blank=True, default='Karen', max_length=10),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='city',
            field=models.CharField(blank=True, default='Nairobi', max_length=10),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=10),
        ),
    ]
