# Generated by Django 4.0.2 on 2023-06-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_personalprofile_area_personalprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprofile',
            name='grade',
            field=models.IntegerField(default=1),
        ),
    ]
