# Generated by Django 4.0.2 on 2023-06-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_guardian_supervisor_alter_myuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
