# Generated by Django 4.0.2 on 2023-06-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_personalprofile_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='uuid',
            field=models.CharField(default='<function uuid4 at 0x0000014CAEBBEE50>', max_length=100),
        ),
    ]
