# Generated by Django 4.0.2 on 2023-06-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_myuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='uuid',
            field=models.CharField(default='<function uuid4 at 0x000002539373EE50>', max_length=100),
        ),
    ]
