# Generated by Django 4.0.2 on 2023-06-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_myuser_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='uuid',
        ),
    ]
