# Generated by Django 4.2.3 on 2023-07-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_myuser_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField()),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='academicprofile',
            name='grade',
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='pic',
            field=models.ImageField(default='\\profile_pics\\TT.png', upload_to='profile_pics/'),
        ),
    ]
