# Generated by Django 4.2.3 on 2023-07-18 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_schoolclass_remove_academicprofile_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprofile',
            name='current_class',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Users.schoolclass'),
        ),
    ]
