# Generated by Django 4.2.3 on 2023-07-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_academicprofile_current_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='class_size',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
