# Generated by Django 4.2.3 on 2023-08-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_schoolclass_class_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalprofile',
            name='pic',
        ),
    ]
